coverage:
  status:
    patch:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
    project:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
ignore:
  - "*/usr/include/*"
  - "*/build/_deps/*"
  - "*/tests/*"
