coverage:
  status:
    patch:
      default:
        target: 90%
        threshold: 0%
        if_ci_failed: error
    project:
      default:
        target: 90%
        threshold: 0%
        if_ci_failed: error
ignore:
  - 'tests/*'
